CREATE DATABASE DB_IMAGEM1;

USE DB_IMAGEM1;

CREATE TABLE MOTHERS (
    ID INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    CONSTRAINT PK_MAE PRIMARY KEY (ID)
);

CREATE TABLE BABIES (
    ID INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    BIRTH_WEIGHT NUMERIC NOT NULL,
    HEIGHT NUMERIC NOT NULL,
    MOTHER_ID INT NOT NULL,
    CONSTRAINT PK_BABIES PRIMARY KEY (ID),
    CONSTRAINT FK_BABIES_MOTHERS FOREIGN KEY (MOTHER_ID) REFERENCES MOTHERS(ID)
);

CREATE TABLE DOCTORS (
    ID_DOCTOR INT NOT NULL,
    CRM VARCHAR(100) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    ESPECIALIDADE VARCHAR(50) NOT NULL,
    CONSTRAINT PK_DOCTORS PRIMARY KEY (ID_DOCTOR)
);

CREATE TABLE CONSULTA (
    BABY_ID INT NOT NULL,
    DOCTOR_ID INT NOT NULL,
    SERVICE_DATE DATE NOT NULL,
    SERVICE_TIME TIME NOT NULL,
    CONSTRAINT PK_CONSULTA PRIMARY KEY (BABY_ID, DOCTOR_ID, SERVICE_DATE),
    CONSTRAINT FK_CONSULTA_BABY FOREIGN KEY (BABY_ID) REFERENCES BABIES(ID),
    CONSTRAINT FK_CONSULTA_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(ID_DOCTOR)
);




