CREATE DATABASE DB_IMAGEM3;
USE DB_IMAGEM3;

CREATE TABLE SETORES(
    ID_SETOR INT NOT NULL,
    NUM_SETOR VARCHAR(100) NOT NULL,
    LOCAL VARCHAR(100) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_SETORES PRIMARY KEY(ID_SETOR)
);
CREATE TABLE FUNCIONARIOS(
    ID_FUNCIONARIO INT NOT NULL,
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
    GENERO VARCHAR(100) NOT NULL,
    SALARIO NUMERIC NOT NULL,
    CPF VARCHAR(100) NOT NULL,
    MANAGER_ID INT NOT NULL,
    SETOR_ID INT NOT NULL,
    CONSTRAINT PK_FUNCIONARIOS PRIMARY KEY(ID_FUNCIONARIO),
    CONSTRAINT FK_FUNCIONARIOS_SETORES FOREIGN KEY (SETOR_ID) REFERENCES SETORES (ID_SETOR)
);	