CREATE DATABASE DB_IMAGEM2;
USE DB_IMAGEM2;
CREATE TABLE CONSUMIDOR (
    ID_CONSUMIDOR INT NOT NULL, 
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(100) NOT NULL,
    ENDEREÇO VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CONSUMIDOR PRIMARY KEY(ID_CONSUMIDOR)
);

CREATE TABLE PRODUTO (
    ID_PRODUTO INT NOT NULL,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL,
    PRECO_UNITARIO NUMERIC(10,2) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY(ID_PRODUTO)
);

CREATE TABLE COMPRADOS (
    ID INT NOT NULL,
    ID_CONSUMIDOR INT NOT NULL,
    DATA_COMPRA TIMESTAMP NOT NULL,
    VALOR_TOTAL NUMERIC(10,2) NOT NULL,
    CONSTRAINT PK_COMPRADOS PRIMARY KEY(ID),
    CONSTRAINT FK_COMPRADOS_CONSUMIDOR FOREIGN KEY (ID_CONSUMIDOR) 
        REFERENCES CONSUMIDOR(ID_CONSUMIDOR)
);

CREATE TABLE PRODUTOSCOMPRADOS (
    ID_COMPRA INT NOT NULL,
    COMPRA_ID INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    CONSTRAINT PK_PRODUTOSCOMPRADOS PRIMARY KEY(ID_COMPRA),
    CONSTRAINT FK_PRODUTOSCOMPRADOS_COMPRA FOREIGN KEY (COMPRA_ID) 
	REFERENCES COMPRADOS(ID),
    CONSTRAINT FK_PRODUTOSCOMPRADOS_PRODUTO FOREIGN KEY (ID_PRODUTO) 
	REFERENCES PRODUTO(ID_PRODUTO)
);

INSERT INTO CONSUMIDOR (ID_CONSUMIDOR,NOME,TELEFONE,ENDERECO) VALUES
	('1','Estevan', '(11)99999-9999)', 'Rua dos Alfeneiros'),
	('2','Sarah', '(22)99999-9999)', 'Rua da Minha Casa'),
	('','Gabi', '(33)99999-9999)', 'Rua Legal'),
	('','Emerson', '(44)99999-9999)', 'Rua Belterra'),
	('','Jeferson', '(55)99999-9999)', 'Rua Oliveira'),
	('','João', '(66)99999-9999)', 'Rua Alves'),
	('','José', '(77)99999-9999)', 'Rua Adriana'),
	('','Mazé', '(88)99999-9999)', 'Rua Medeiros'),
	('','Casemiro', '(99)99999-9999)', 'Rua Lourenço'),
	('','Castro', '(19)99999-9999)', 'Rua Azul');
    
INSERT INTO PRODUTO (NOME_PRODUTO,TIPO,PRECO_UNITARIO) VALUES
	('Pedra','Natural','9,90'),
	('Máquina de Lavar','Eletrodomésticos','590,90'),
	('Mortadela','Alimentos','14,90'),
	('Garrafa de água','Alimentos','5,90'),
	('Camisa Azul','Moda','54,90'),
	('Gel de Cabelo','Hígiene','4,90'),
	('Delineador','Maquiagem','14,90'),
	('Banana','Alimentos','9,90'),
	('Óculos','Moda','149,90'),
	('Colírio','Remédios','9,90');
    
INSERT INTO COMPRADOS () VALUES



